---
title: "Figures for paper"
author: "pz"
date: "2022-09-21; updated `r Sys.Date()`"
output:
    html_document:
        toc: true
        toc_depth: 6
        toc_float: true
        code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache=FALSE, cache.lazy = FALSE)
```

```{r eval=TRUE, include=FALSE }
library(SingleCellExperiment);library(magrittr);
library(data.table)
library(scater)
library(patchwork);library(ggplot2)
library(knitr)
library(grid)
library(gridExtra)
library(ggtext)
library(ggpubr)
library(ggtext)
theme_set(theme_bw(base_size = 16))
```

```{r read_in_sce}
sce <- readRDS("sce_allSamples_sampleIntegration_relabeled_2022-09-06.rds")
```


```{r adjust_nomenclature}
cdata = colData(sce)
cdata$label = ""
cdata[cdata$TISCHCelltype.Major == "Malignant.Blood",]$label = "Malignant-Heme"
cdata[cdata$TISCHCelltype.Major == "B_CLL",]$label = "Malignant-CLL"
cdata[cdata$TISCHCelltype.Major == "Malignant.Solid",]$label = "Malignant-Solid"
cdata[cdata$TISCHCelltype.Major == "Fibroblasts",]$label = "Fibroblast"
cdata[cdata$TISCHCelltype.Major == "Epithelial",]$label = "Epithelial cell"
cdata[cdata$TISCHCelltype.Major == "Endothelial",]$label = "Endothelial cell"
cdata[cdata$TISCHCelltype.Major == "Mono/Macro",]$label = "Mono/MP"
cdata[cdata$TISCHCelltype.Major == "DC",]$label = "DC"
cdata[cdata$TISCHCelltype.Major == "Mast",]$label = "Mast cell"
cdata[cdata$TISCHCelltype.Major == "Erythrocytes",]$label = "Erythrocyte"
cdata[cdata$TISCHCelltype.Major == "B",]$label = "B cell"
cdata[cdata$TISCHCelltype.Major == "Plasma",]$label = "Plasma cell"
cdata[cdata$TISCHCelltype.Major == "Treg",]$label = "CD4+ Treg"
cdata[cdata$TISCHCelltype.Major == "CD4Tconv",]$label = "CD4+ Tcon"
cdata[cdata$TISCHCelltype.Major == "CD8T",]$label = "CD8+ T"
cdata[cdata$TISCHCelltype.Major == "Tprolif",]$label = "Tprolif"
cdata[cdata$TISCHCelltype.Major == "CD8Tex",]$label = "CD8+ Tex"
cdata[cdata$TISCHCelltype.Major == "NK",]$label = "NK cell"
#cdata[cdata$TISCHCelltype.Major == "NA",]$label = "Not defined"
colData(sce) = cdata


sce$label = factor(sce$label, 
                   levels=rev(c("NK cell",
                            "CD8+ Tex",
                            "Tprolif",
                            "CD8+ T",
                            "CD4+ Tcon",
                            "CD4+ Treg",
                            "Plasma cell",
                            "B cell",
                            "Erythrocyte",
                            "Mast cell",
                            "DC",
                            "Mono/MP",
                            "Endothelial cell",
                            "Epithelial cell",
                            "Fibroblast",
                            "Malignant-Solid",
                            "Malignant-CLL",
                            "Malignant-Heme")))
```



# Total number of cells 

```{r}
num_cells = rbind(reshape2::melt(table(sce$Dataset)), data.frame(Var1="total cells", value=ncol(sce)))
colnames(num_cells) = c("dataset", "num_cells")
knitr::kable(num_cells)
```



# UMAP

```{r plotReducedDim2_func, eval=T, context="data",results="asis", fig.width=10, fig.height=10, cache=F}
plotReducedDim2 <- function (object, dimred, ncomponents = 2, percentVar = NULL, 
  colour_by = NULL, shape_by = NULL, size_by = NULL, by_exprs_values = "logcounts", 
  text_by = NULL, text_size = 5, text_colour = "black", label_format = c("%s %i", 
    " (%i%%)"), other_fields = list(), swap_rownames = NULL, order_cells = FALSE,
  ...) 
{
  red_dim <- as.matrix(reducedDim(object, dimred))
  if (any(ncomponents > ncol(red_dim))) {
    stop(sprintf("'ncomponents' is larger than 'ncols(reducedDim(object,'%s'))'", 
      dimred))
  }
  if (is.null(percentVar)) {
    percentVar <- attr(red_dim, "percentVar")
  }
  if (length(ncomponents) == 1L) {
    to_plot <- seq_len(ncomponents)
  }
  else {
    to_plot <- ncomponents
  }
  colnames(red_dim) <- NULL
  df_to_plot <- data.frame(red_dim[, to_plot, drop = FALSE])
  vis_out <- scater:::.incorporate_common_vis_col(df_to_plot, se = object, 
    colour_by = colour_by, shape_by = shape_by, size_by = size_by, 
    by_exprs_values = by_exprs_values, other_fields = other_fields, 
    swap_rownames = swap_rownames)
  df_to_plot <- vis_out$df
  colour_by <- vis_out$colour_by
  shape_by <- vis_out$shape_by
  size_by <- vis_out$size_by
  if(order_cells==TRUE){
    if(colour_by %in% row.names(object)){
      df_to_plot$order_cells_by <- assay(object, by_exprs_values)[colour_by,]
      df_to_plot = df_to_plot %>% plyr::arrange(order_cells_by)  
    } else {
      df_to_plot$order_cells_by <- colData(object)[,colour_by]
      df_to_plot = df_to_plot %>% plyr::arrange(order_cells_by) 
    }
  }
  if (length(to_plot) == 2L) {
    colnames(df_to_plot)[seq_along(to_plot)] <- c("X", "Y")
    labs <- sprintf(label_format[1], dimred, to_plot)
    if (!is.null(percentVar)) {
      labs <- paste0(labs, sprintf(label_format[2], round(percentVar[to_plot])))
    }
    plot_out <- scater:::.central_plotter(df_to_plot, xlab = labs[1], 
      ylab = labs[2], colour_by = colour_by, size_by = size_by, 
      shape_by = shape_by, ..., point_FUN = NULL)
    if (!is.null(text_by)) {
      text_out <- retrieveCellInfo(object, text_by, search = "colData")
      text_out$val <- scater:::.coerce_to_factor(text_out$val, 
        level.limit = Inf)
      by_text_x <- vapply(split(df_to_plot$X, text_out$val), 
        median, FUN.VALUE = 0)
      by_text_y <- vapply(split(df_to_plot$Y, text_out$val), 
        median, FUN.VALUE = 0)
      plot_out <- plot_out + geom_text_repel(data = data.frame(x = by_text_x, 
        y = by_text_y, label = names(by_text_x)), mapping = aes(x = x, 
        y = y, label = label), inherit.aes = FALSE, 
        size = text_size, colour = text_colour)
    }
    return(plot_out)
  }
  scater:::paired_reddim_plot(df_to_plot, to_plot = to_plot, percentVar = percentVar, 
    colour_by = colour_by, shape_by = shape_by, size_by = size_by, 
    dimred = dimred, label_format = label_format, ...)
}
```

```{r colors, eval=T, context="data",results="asis", fig.width=10, fig.height=10, cache=F}
DefaultContColorPalette = c("#d4d4d4","#d0cfd2","#cccbd0","#c9c7cf","#c5c3cd","#c1becc","#bebaca","#bab6c9","#b6b2c7","#b3aec5","#afa9c4","#aba5c2","#a8a1c1","#a49dbf","#a098be","#9d94bc","#9990ba","#958cb9","#9287b7","#8e83b6","#8a7fb4","#877bb2","#8377b1","#7f72af","#7c6eae","#786aac","#7466ab","#7161a9","#6d5da7","#6959a6","#6555a4","#6250a3","#5e4ca1","#5a489f","#57449e","#533f9c","#4f3b9b","#4c3799","#483398","#442f96","#412a94","#3d2693","#392291","#361e90","#32198e","#2e158d","#2b118b","#270d89","#230888","#200486","#1c0085")

DiscColorPalette = c(
  "B" ="#E58606", 
  "B_CLL" =  "#5D69B1", 
  "CD4Tconv" =  "#E9CB58", 
  "CD8T" =   "#BD65AB", 
  "CD8Tex" =  "#DD6559", 
  "DC" =  "#24796C",
  "Endothelial" =   "#DAA51B", 
  "Epithelial" =  "#2F8AC4", 
  "Erythrocytes" = "#764E9F", 
  "Fibroblasts" =  "black", #ED645A
  "Malignant.Blood" =  "#A5AA99",
  "Malignant.Solid" = "#a9aba4", 
  "Mast" =   "#BCBD22",
  "Mono/Macro" =   "#B279A2", 
  "NK" =   "#6FBAA4", 
  "Plasma" =   "#17BECF", 
  "Tprolif" =  "#5B66AA", 
  "Treg" =   "#A9ABA4")





DiscColorPalette = c(
  "B cell" ="#E58606", 
  "Malignant-CLL" =  "#5D69B1", 
  "CD4+ Tcon" =  "#E9CB58", 
  "CD8+ T" =   "#BD65AB", 
  "CD8+ Tex" =  "#DD6559", 
  "DC" =  "#24796C",
  "Endothelial cell" =   "#DAA51B", 
  "Epithelial cell" =  "#2F8AC4", 
  "Erythrocyte" = "#764E9F", 
  "Fibroblast" =  "black",
  "Malignant-Heme" =  "#A5AA99",
  "Malignant-Solid" = "#a9aba4", 
  "Mast cell" =   "#BCBD22",
  "Mono/MP" =   "#B279A2", 
  "NK cell" =   "#6FBAA4", 
  "Plasma cell" =   "#17BECF", 
  "Tprolif" =  "#5B66AA", 
  "CD4+ Treg" =   "#A9ABA4")



```

## UMAP


```{r umap, eval=T, context="data",results="asis", fig.width=7, fig.height=5.5, cache=F, fig.path='2023-07_figuresForPaper_v2/', dev=c('png','pdf')}
p1 = plotReducedDim(sce, dimred="UMAP", text_by = NULL, colour_by="label", point_alpha=0.7, point_size=0.005, text_size=4, other_fields="Condition") + 
  theme_bw()  + 
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position="right") + 
  guides(colour = guide_legend(override.aes = list(size=2,alpha = 1))) +
  scale_colour_manual(values=DiscColorPalette, name="", ) +
  ggtitle(expr(paste("n=",  "244,809"," cells",sep=""))) +
  ggeasy::easy_center_title() +
  xlab("") + ylab("") + guides(colour = guide_legend(override.aes = list(size=2,alpha = 1), ncol=2))
p1_zoom =  p1 +  coord_cartesian(ylim=c(-3,4), xlim=c(-8,0.7)) + ggtitle("")

print(p1)

```



```{r umap_superscript, eval=T, context="data",results="asis", fig.width=7, fig.height=5.5, cache=F, fig.path='2023-07_figuresForPaper_v2/', dev=c('png','pdf')}
p1 = plotReducedDim(sce, dimred="UMAP", text_by = NULL, colour_by="label", point_alpha=0.7, point_size=0.005, text_size=4, other_fields="Condition") + 
  theme_bw()  +  scale_colour_manual(values=DiscColorPalette, name="", labels=c(rev(c("NK cell",
      "CD8<sup>+</sup> Tex",
      "Tprolif",
      "CD8<sup>+</sup> T",
      "CD4<sup>+</sup> Tcon",
      "CD4<sup>+</sup> Treg",
      "Plasma cell",
      "B cell",
      "Erythrocyte",
      "Mast cell",
      "DC",
      "Mono/MP",
      "Endothelial cell",
      "Epithelial cell",
      "Fibroblast",
      "Malignant-Solid",
      "Malignant-CLL",
      "Malignant-Heme")))) + 
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position="right",
        legend.text  = element_markdown()) + 
  guides(colour = guide_legend(override.aes = list(size=2,alpha = 1))) +
  ggtitle(expr(paste("n=",  "244,809"," cells",sep=""))) +
  ggeasy::easy_center_title() +
  xlab("") + ylab("") + guides(colour = guide_legend(override.aes = list(size=2,alpha = 1), ncol=2))
p1_zoom =  p1 +  coord_cartesian(ylim=c(-3,4), xlim=c(-8,0.7)) + ggtitle("")

print(p1)
#print(p1_zoom + theme(legend.position="none" ))
```


```{r umap_noLegend_noLabels, eval=T, context="data",results="asis", fig.width=5, fig.height=5.5, cache=F, fig.path='2023-07_figuresForPaper_v2/', dev=c('png','pdf')}
p1 = plotReducedDim(sce, dimred="UMAP", text_by = NULL, colour_by="label", point_alpha=0.7, point_size=0.005, text_size=4, other_fields="Condition") + 
  theme_bw()  + 
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position="none") + 
  guides(colour = guide_legend(override.aes = list(size=2,alpha = 1))) +
  scale_colour_manual(values=DiscColorPalette, name="") +
  ggtitle("") +
  ggeasy::easy_center_title() +
  xlab("") + ylab("") + guides(colour = guide_legend(override.aes = list(size=2,alpha = 1), ncol=2))

print(p1)
#print(p1_zoom + theme(legend.position="none" ))
```




```{r umap_noLegend_noLabels_zoom, eval=T, context="data",results="asis", fig.width=5, fig.height=5.5, cache=F, fig.path='2023-07_figuresForPaper_v2/', dev=c('png','pdf')}
p1 = plotReducedDim(sce, dimred="UMAP", text_by = NULL, colour_by="label", point_alpha=0.7, point_size=0.005, text_size=4, other_fields="Condition") + 
  theme_bw()  + 
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position="right") + 
  guides(colour = guide_legend(override.aes = list(size=2,alpha = 1))) +
  scale_colour_manual(values=DiscColorPalette, name="", ) +
  ggtitle(expr(paste("n=",  "244,809"," cells",sep=""))) +
  ggeasy::easy_center_title() +
  xlab("") + ylab("") + guides(colour = guide_legend(override.aes = list(size=2,alpha = 1), ncol=2))
p1_zoom =  p1 +  coord_cartesian(ylim=c(-3,4), xlim=c(-8,0.7)) + ggtitle("")
print(p1_zoom + theme(legend.position="none" ))
```




```{r FASLG_alone, eval=T, context="data",results="asis", fig.width=5, fig.height=5.5, cache=F, fig.path='2023-07_figuresForPaper_v2/', dev=c('png','pdf')}
gene = "FASLG"
p2 = plotReducedDim2(sce, dimred="UMAP", colour_by=gene, point_alpha=0.6, point_size=0.005, text_size=4, other_fields="Condition", order_cells=TRUE) +
  theme_bw()  +
    theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position="bottom") +
  scale_colour_gradientn(colours = DefaultContColorPalette, name="")  +
  guides(colour=guide_colourbar(barheight =0.8,barwidth=20,label.position="bottom")) +
  ggtitle(expr(paste(italic(!!gene),sep=""))) + 
  ggeasy::easy_center_title() +
  xlab("") + ylab("") 
print(p2)
```




```{r FAS_alone, eval=T, context="data",results="asis", fig.width=5, fig.height=5.5, cache=F, fig.path='2023-07_figuresForPaper_v2/', dev=c('png','pdf')}
gene = "FAS"
p3 =plotReducedDim2(sce, dimred="UMAP", colour_by=gene, point_alpha=0.6, point_size=0.005, text_size=4, other_fields="Condition", order_cells=TRUE) +
  theme_bw()  +
    theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position="bottom") +
  scale_colour_gradientn(colours = DefaultContColorPalette, name="")  +
  guides(colour=guide_colourbar(barheight =0.8,barwidth=20,label.position="bottom")) +
  ggtitle(expr(paste(italic(!!gene),sep=""))) + 
  ggeasy::easy_center_title() +
  xlab("") + ylab("") 
print(p3)
```


```{r FASLG_FASLG_combined, eval=T, context="data",results="asis", fig.width=11, fig.height=5.5, cache=F, fig.path='2023-07_figuresForPaper_v2/', dev=c('png','pdf')}
gene = "FASLG"
p2 = plotReducedDim2(sce, dimred="UMAP", colour_by=gene, point_alpha=0.6, point_size=0.005, text_size=4, other_fields="Condition", order_cells=TRUE) +
  theme_bw()  +
    theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position="bottom") +
  scale_colour_gradientn(colours = DefaultContColorPalette, name="")  +
  guides(colour=guide_colourbar(barheight =0.8,barwidth=20,label.position="bottom")) +
  ggtitle(expr(paste(italic(!!gene),sep=""))) + 
  ggeasy::easy_center_title() +
  xlab("") + ylab("") 

gene = "FAS"
p3 =plotReducedDim2(sce, dimred="UMAP", colour_by=gene, point_alpha=0.6, point_size=0.005, text_size=4, other_fields="Condition", order_cells=TRUE) +
  theme_bw()  +
    theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position="bottom") +
  scale_colour_gradientn(colours = DefaultContColorPalette, name="")  +
  guides(colour=guide_colourbar(barheight =0.8,barwidth=20,label.position="bottom")) +
  ggtitle(expr(paste(italic(!!gene),sep=""))) + 
  ggeasy::easy_center_title() +
  xlab("") + ylab("") 


ggpubr::ggarrange(p2, p3, ncol=2, nrow=1, common.legend = TRUE, legend="bottom")
```


## Violin


```{r vilnplots_dittoseq, eval=T, fig.width = 6, fig.height = 5, warning=FALSE, message=FALSE, fig.path='2023-07_figuresForPaper_v2/', dev=c('png','pdf')}
sce$label = factor(sce$label, 
                   levels=c("NK cell",
                            "CD8+ Tex",
                            "Tprolif",
                            "CD8+ T",
                            "CD4+ Tcon",
                            "CD4+ Treg",
                            "Plasma cell",
                            "B cell",
                            "Erythrocyte",
                            "Mast cell",
                            "DC",
                            "Mono/MP",
                            "Endothelial cell",
                            "Epithelial cell",
                            "Fibroblast",
                            "Malignant-Solid",
                            "Malignant-CLL",
                            "Malignant-Heme"))

p1 = scater::plotExpression(sce, "FAS", x="label", colour_by="label", point_alpha=0.8, point_size=0.2, scales="free_y", show_violin=FALSE,ncol=1) + scale_colour_manual(values=DiscColorPalette, name="")  + theme_bw()  + theme( panel.border = element_blank()) + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) + theme(strip.background = element_blank(), strip.text.x = element_text(face = "italic", size=12)) + theme(legend.position = "none") +xlab("")  + ggeasy::easy_center_title() + theme(plot.title = element_text(face="bold"))  + coord_flip() + scale_y_reverse() + ylab("Expression\n(log counts)")  + theme(plot.margin = margin(5.5, 0, 5.5, 0, "pt"))

p2 = scater::plotExpression(sce, "FASLG", x="label", colour_by="label", point_alpha=0.8, point_size=0.2, scales="free_y", show_violin=FALSE,ncol=1) + scale_colour_manual(values=DiscColorPalette, name="")  + theme_bw()  + theme( panel.border = element_blank()) + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) + theme(strip.background = element_blank(), strip.text.x = element_text(face = "italic", size=12)) + theme(legend.position = "none") +xlab("")  + ggeasy::easy_center_title() + theme(plot.title = element_text(face="bold")) + coord_flip()  + scale_x_discrete(position = "top") + ylab("Expression\n(log counts)") + theme(plot.margin = margin(5.5, 0, 5.5, 0, "pt"))

pw <- p1 + p2 
pw + plot_annotation(title = "")
```

### % of cells with positive expression


```{r stats,eval=T, fig.width = 9, fig.height = 5, warning=FALSE, message=FALSE}
num_cells_per_type = table(sce$label)

keep = colnames(sce)[which(as.numeric(assay(sce["FASLG",head(colnames(sce), Inf)])) > 0)]
num_pos_cells_faslg =  table(sce[,keep]$label)

merged = merge(melt(num_cells_per_type), melt(num_pos_cells_faslg), by="Var1", all=T)
merged$percentFaslg = (merged$value.y/merged$value.x)*100

keep = colnames(sce)[which(as.numeric(assay(sce["FAS",head(colnames(sce), Inf)])) > 0)]
num_pos_cells_fas =  table(sce[,keep]$label)
merged = merge(merged, melt(num_pos_cells_fas), by="Var1", all=T)
merged$percentFas = (merged$value/merged$value.x)*100

colnames(merged) = c("Celltype", "totalNumCells", "cellsWithGt0FaslgCount", "PerPosFASLG", "cellsWithGt0FasCount",  "PerPosFAS")
merged$PerPosFAS = sprintf("%.2f",(round(merged$PerPosFAS, digits=2))) #round( merged$PerPosFAS, digits=2)
merged$PerPosFASLG = sprintf("%.2f",(round(merged$PerPosFASLG, digits=2))) #round( merged$PerPosFASLG, digits=2)

row.names(merged) = merged$Celltype
merged = merged[rev(levels(sce$label)),]

merged$Celltype2 = rev(c("NK cell",
      "CD8<sup>+</sup> Tex",
      "Tprolif",
      "CD8<sup>+</sup> T",
      "CD4<sup>+</sup> Tcon",
      "CD4<sup>+</sup> Treg",
      "Plasma cell",
      "B cell",
      "Erythrocyte",
      "Mast cell",
      "DC",
      "Mono/MP",
      "Endothelial cell",
      "Epithelial cell",
      "Fibroblast",
      "Malignant-Solid",
      "Malignant-CLL",
      "Malignant-Heme"))
knitr::kable(merged, row.names = F)
```




```{r vilnplots_percent,eval=T, fig.width = 6, fig.height = 5, warning=FALSE, message=FALSE, fig.path='2023-07_figuresForPaper_v2/', dev=c('png','pdf')}
p1 = scater::plotExpression(sce, "FAS", x="label", colour_by="label", point_alpha=0.8, point_size=0.2, scales="free_y", show_violin=FALSE,ncol=1) + scale_colour_manual(values=DiscColorPalette, name="")  + theme_bw()  + theme( panel.border = element_blank()) + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) + theme(strip.background = element_blank(), strip.text.x = element_text(face = "italic", size=12)) + theme(legend.position = "none") +xlab("")  + ggeasy::easy_center_title() + theme(plot.title = element_text(face="bold"))  + coord_flip() + scale_y_reverse() + ylab("Expression\n(log counts)")  + theme(plot.margin = margin(5.5, 0, 5.5, 0, "pt")) + theme( axis.ticks = element_blank()) + scale_x_discrete(labels=rev(paste0(merged$Celltype," - (",merged$PerPosFAS,"%)")))

p2 = scater::plotExpression(sce, "FASLG", x="label", colour_by="label", point_alpha=0.8, point_size=0.2, scales="free_y", show_violin=FALSE,ncol=1) + scale_colour_manual(values=DiscColorPalette, name="")  + theme_bw()  + theme( panel.border = element_blank()) + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) + theme(strip.background = element_blank(), strip.text.x = element_text(face = "italic", size=12)) + theme(legend.position = "none") +xlab("")  + ggeasy::easy_center_title() + theme(plot.title = element_text(face="bold")) + coord_flip()  + scale_x_discrete(position = "top", labels=rev(paste0("(",merged$PerPosFASLG,"%)"))) + ylab("Expression\n(log counts)") + theme(plot.margin = margin(5.5, 0, 5.5, 0, "pt")) + theme( axis.ticks = element_blank()) 

pw <- p1 + p2 
pw + plot_annotation(title = "")
```


## Dot plot (min percent = 0.05)


```{r dotplot_0.5, eval=T, fig.height = 5, fig.width = 3, message=FALSE, fig.path='2023-07_figuresForPaper_v2/', dev=c('png','pdf')}
genes = c("FAS", "FASLG")

p1 = dittoSeq::dittoDotPlot(sce, vars = genes, group.by = "label", assay="logcounts",  scale=F, max.percent=1, min.percent = 0.05)   + theme_bw()  + theme( panel.border = element_blank()) + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, size=10), axis.text.y = element_text(size=10)) + ggtitle("") + theme(axis.text.x = element_text(face = "italic")) + scale_size(name = "percent\nexpression",limits = c(0.05, 1),range = c(0, 7), breaks=c(0.05, 0.10, 0.25, 0.50, 0.75, 1), labels=c(c(0.05, 0.10, 0.25, 0.50, 0.75, 1)*100))  + scale_color_gradient2(low = "gray",mid = "white", high = "darkblue", name = 'average\nexpression')  +  guides(size = guide_legend(order = 2), colour = guide_colorbar(order = 1)) 


legend = ggpubr::get_legend(p1)
dotplot_dat = p1$data
#ggpubr::as_ggplot(legend)

```


## violin with dot

```{r vilnplots_with_dot_percent, eval=T, fig.width = 6, fig.height = 5, warning=FALSE, message=FALSE,  fig.path='2023-07_figuresForPaper_v2/', dev=c('png','pdf')}
p1 = scater::plotExpression(sce, "FAS", x="label", colour_by="label", point_alpha=0.8, point_size=0.2, scales="free_y", show_violin=FALSE,ncol=1) + scale_colour_manual(values=DiscColorPalette, name="") + scale_fill_manual(values=DiscColorPalette, name="")  + theme_bw()  + theme( panel.border = element_blank()) + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) + theme(strip.background = element_blank(), strip.text.x = element_text(face = "italic", size=12)) + theme(legend.position = "none") +xlab("")  + ggeasy::easy_center_title() + theme(plot.title = element_text(face="bold"))  + coord_flip() + scale_y_reverse() + ylab("Expression\n(log counts)")  + theme(plot.margin = margin(5.5, 0, 5.5, 0, "pt")) + theme( axis.ticks = element_blank()) + scale_x_discrete(labels=rev(paste0(merged$Celltype," - (",merged$PerPosFAS,"%)"))) + ggnewscale::new_scale_color() + geom_point(data=subset(dotplot_dat, var == "FAS"),  aes(y = 4, x = grouping, color = color, size = size)) + scale_size(name = "percent\nexpression",limits = c(0.05, 1),range = c(0, 7), breaks=c(0.05, 0.10, 0.25, 0.50, 0.75, 1),labels=c(c(0.05, 0.10, 0.25, 0.50, 0.75, 1)*100))  + scale_color_gradient2(low = "gray",mid = "white", high = "darkblue", name = 'average\nexpression')

p2 = scater::plotExpression(sce, "FASLG", x="label", colour_by="label", point_alpha=0.8, point_size=0.2, scales="free_y", show_violin=FALSE,ncol=1) + scale_colour_manual(values=DiscColorPalette, name="")  + theme_bw()  + theme( panel.border = element_blank()) + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) + theme(strip.background = element_blank(), strip.text.x = element_text(face = "italic", size=12)) + theme(legend.position = "none") +xlab("")  + ggeasy::easy_center_title() + theme(plot.title = element_text(face="bold")) + coord_flip()  + scale_x_discrete(position = "top", labels=rev(paste0("(",merged$PerPosFASLG,"%)"))) + ylab("Expression\n(log counts)") + theme(plot.margin = margin(5.5, 0, 5.5, 0, "pt")) + theme( axis.ticks = element_blank())   + ggnewscale::new_scale_color() + geom_point(data=subset(dotplot_dat, var == "FASLG"),  aes(y = 4, x = grouping, color = color, size = size)) + scale_size(name = "percent\nexpression",limits = c(0.05, 1),range = c(0, 7), breaks=c(0.05, 0.10, 0.25, 0.50, 0.75, 1),labels=c(c(0.05, 0.10, 0.25, 0.50, 0.75, 1)*100))  + scale_color_gradient2(low = "gray",mid = "white", high = "darkblue", name = 'average\nexpression')

pw <- p1 + p2 
pw + plot_annotation(title = "")

```


```{r vilnplots_with_dot_percent_width6, eval=T, fig.width = 6, fig.height = 5, warning=FALSE, message=FALSE,  fig.path='2023-07_figuresForPaper_v2/', dev=c('png','pdf')}
p3 =  ggpubr::as_ggplot(legend)
pw <- p1 + p2 + p3
pw + plot_layout(widths = c(1, 1, 0.5)) + plot_annotation(title = "")
```

```{r vilnplots_with_dot_percent_width6.5, eval=T, fig.width = 6.5, fig.height = 5, warning=FALSE, message=FALSE,  fig.path='2023-07_figuresForPaper_v2/', dev=c('png','pdf')}
p3 =  ggpubr::as_ggplot(legend)
pw <- p1 + p2 + p3
pw + plot_layout(widths = c(1, 1, 0.5)) + plot_annotation(title = "")
```







```{r vilnplots_with_dot_percent_width6.5_shade,eval=T,  fig.width = 6.5, fig.height = 5, warning=FALSE, message=FALSE,  fig.path='2023-07_figuresForPaper_v2/', dev=c('png','pdf')}
library(gginnards)
p1 = scater::plotExpression(sce, "FAS", x="label", colour_by="label", point_alpha=0.8, point_size=0.2, scales="free_y", show_violin=FALSE,ncol=1)  + scale_colour_manual(values=DiscColorPalette, name="") + scale_fill_manual(values=DiscColorPalette, name="")  + theme_bw()  + theme( panel.border = element_blank()) + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) + theme(strip.background = element_blank(), strip.text.x = element_text(face = "italic", size=12)) + theme(legend.position = "none") +xlab("")  + ggeasy::easy_center_title() + theme(plot.title = element_text(face="bold"))  + coord_flip() + scale_y_reverse() + ylab("Expression\n(log counts)")  + theme(plot.margin = margin(5.5, 0, 5.5, 0, "pt")) + theme( axis.ticks = element_blank()) + scale_x_discrete(labels=rev(paste0(merged$Celltype," - (",merged$PerPosFAS,"%)"))) + ggnewscale::new_scale_color() + geom_point(data=subset(dotplot_dat, var == "FAS"),  aes(y = 4, x = grouping, color = color, size = size)) + scale_size(name = "percent\nexpression",limits = c(0.05, 1),range = c(0, 7), breaks=c(0.05, 0.10, 0.25, 0.50, 0.75, 1),labels=c(c(0.05, 0.10, 0.25, 0.50, 0.75, 1)*100))  + scale_color_gradient2(low = "gray",mid = "white", high = "darkblue", name = 'average\nexpression')  + geom_rect( aes(xmin = 0, xmax = 8.5, ymin = 0, ymax = 4),fill = "#f5faef", alpha = 0.2)  + geom_rect( aes(xmin = 12.5, xmax = 15.5, ymin = 0, ymax = 4),fill = "#eaf1fb", alpha = 0.2) 

p1 = move_layers(p1, position="bottom", idx=3L)
p1 = move_layers(p1, position="bottom", idx=4L)
#print(p1)









p2 = scater::plotExpression(sce, "FASLG", x="label", colour_by="label", point_alpha=0.8, point_size=0.2, scales="free_y", show_violin=FALSE,ncol=1) + scale_colour_manual(values=DiscColorPalette, name="")  + theme_bw()  + theme( panel.border = element_blank()) + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) + theme(strip.background = element_blank(), strip.text.x = element_text(face = "italic", size=12)) + theme(legend.position = "none") +xlab("")  + ggeasy::easy_center_title() + theme(plot.title = element_text(face="bold")) + coord_flip()  + scale_x_discrete(position = "top", labels=rev(paste0("(",merged$PerPosFASLG,"%)"))) + ylab("Expression\n(log counts)") + theme(plot.margin = margin(5.5, 0, 5.5, 0, "pt")) + theme( axis.ticks = element_blank())   + ggnewscale::new_scale_color() + geom_point(data=subset(dotplot_dat, var == "FASLG"),  aes(y = 4, x = grouping, color = color, size = size)) + scale_size(name = "percent\nexpression",limits = c(0.05, 1),range = c(0, 7), breaks=c(0.05, 0.10, 0.25, 0.50, 0.75, 1),labels=c(c(0.05, 0.10, 0.25, 0.50, 0.75, 1)*100))  + scale_color_gradient2(low = "gray",mid = "white", high = "darkblue", name = 'average\nexpression')  + geom_rect( aes(xmin = 0, xmax = 8.5, ymin = 0, ymax = 4),fill = "#f5faef", alpha = 0.2)  + geom_rect( aes(xmin = 12.5, xmax = 15.5, ymin = 0, ymax = 4),fill = "#eaf1fb", alpha = 0.2) 
p2 = move_layers(p2, position="bottom", idx=3L)
p2 = move_layers(p2, position="bottom", idx=4L)
#print(p2)


p3 =  ggpubr::as_ggplot(legend)
pw <- p1 + p2 + p3
pw + plot_layout(widths = c(1, 1, 0.5)) + plot_annotation(title = "")
```








```{r vilnplots_with_dot_percent_superscript_twoDigits, eval=T, fig.width = 6, fig.height = 5, warning=FALSE, message=FALSE,  fig.path='2023-07_figuresForPaper_v2/', dev=c('png','pdf')}
p1 = scater::plotExpression(sce, "FAS", x="label", colour_by="label", point_alpha=0.8, point_size=0.2, scales="free_y", show_violin=FALSE,ncol=1) + scale_colour_manual(values=DiscColorPalette, name="") + scale_fill_manual(values=DiscColorPalette, name="")  + theme_bw()  + theme( panel.border = element_blank()) + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) + theme(strip.background = element_blank(), strip.text.x = element_text(face = "italic", size=12)) + theme(legend.position = "none") +xlab("")  + ggeasy::easy_center_title() + theme(plot.title = element_text(face="bold"))  + coord_flip() + scale_y_reverse() + ylab("Expression\n(log counts)")  + theme(plot.margin = margin(5.5, 0, 5.5, 0, "pt")) + theme( axis.ticks = element_blank()) + scale_x_discrete(labels=rev(paste0(merged$Celltype2," - (",merged$PerPosFAS,"%)"))) + ggnewscale::new_scale_color() + geom_point(data=subset(dotplot_dat, var == "FAS"),  aes(y = 4, x = grouping, color = color, size = size)) + scale_size(name = "percent\nexpression",limits = c(0.05, 1),range = c(0, 7), breaks=c(0.05, 0.10, 0.25, 0.50, 0.75, 1),labels=c(c(0.05, 0.10, 0.25, 0.50, 0.75, 1)*100))  + scale_color_gradient2(low = "gray",mid = "white", high = "darkblue", name = 'average\nexpression')  +   theme( axis.text.x = element_markdown(), axis.text.y = element_markdown())

p2 = scater::plotExpression(sce, "FASLG", x="label", colour_by="label", point_alpha=0.8, point_size=0.2, scales="free_y", show_violin=FALSE,ncol=1) + scale_colour_manual(values=DiscColorPalette, name="")  + theme_bw()  + theme( panel.border = element_blank()) + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) + theme(strip.background = element_blank(), strip.text.x = element_text(face = "italic", size=12)) + theme(legend.position = "none") +xlab("")  + ggeasy::easy_center_title() + theme(plot.title = element_text(face="bold")) + coord_flip()  + scale_x_discrete(position = "top", labels=rev(paste0("(",merged$PerPosFASLG,"%)"))) + ylab("Expression\n(log counts)") + theme(plot.margin = margin(5.5, 0, 5.5, 0, "pt")) + theme( axis.ticks = element_blank())   + ggnewscale::new_scale_color() + geom_point(data=subset(dotplot_dat, var == "FASLG"),  aes(y = 4, x = grouping, color = color, size = size)) + scale_size(name = "percent\nexpression",limits = c(0.05, 1),range = c(0, 7), breaks=c(0.05, 0.10, 0.25, 0.50, 0.75, 1),labels=c(c(0.05, 0.10, 0.25, 0.50, 0.75, 1)*100))  + scale_color_gradient2(low = "gray",mid = "white", high = "darkblue", name = 'average\nexpression')   +   theme( axis.text.x = element_markdown(), axis.text.y = element_markdown())

pw <- p1 + p2 
pw + plot_annotation(title = "")

```


```{r vilnplots_with_dot_percent_superscript_twoDigits_width6, eval=T, fig.width = 6, fig.height = 5, warning=FALSE, message=FALSE,  fig.path='2023-07_figuresForPaper_v2/', dev=c('png','pdf')}
p3 =  ggpubr::as_ggplot(legend)
pw <- p1 + p2 + p3
pw + plot_layout(widths = c(1, 1, 0.5)) + plot_annotation(title = "")
```

```{r vilnplots_with_dot_percent_superscript_twoDigits_width6.5, eval=T, fig.width = 6.5, fig.height = 5, warning=FALSE, message=FALSE,  fig.path='2023-07_figuresForPaper_v2/', dev=c('png','pdf')}
p3 =  ggpubr::as_ggplot(legend)
pw <- p1 + p2 + p3
pw + plot_layout(widths = c(1, 1, 0.5)) + plot_annotation(title = "")
```


# Session Info
```{r session, message=FALSE, warning=FALSE, cache=FALSE,echo=FALSE, fig.width=10, fig.height=5.5, context="data"}
sessionInfo()
```
